services:
  api:
    container_name: web-api
    image: node:22.16.0
    working_dir: /app/api
    env_file:
      - ./api/.env
    volumes:
      - "./api:/app/api"
    ports:
      - "4000:3000"
    command: ["npm", "run", "start:dev"]
  db:
    container_name: web-db
    image: postgres:17.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - "5000:5432"
    volumes:
      - "./db:/var/lib/postgresql/data"
volumes:
  db:
    driver: local
