services:
  api:
    container_name: web-api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    ports:
      - "4000:3000"
    depends_on:
      - db

  db:
    container_name: web-db
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - "5000:5432"
    volumes:
      - './db:/var/lib/postgresql/data'
volumes:
  db:
    driver: local
